### ISSUE TITLE
Update this plugin for Capacitor 3

### ISSUE THREAD

**Issue by mklipe** [capacitor-community/firebase-analytics#46]
Capacitor 3 is being built and is already in [beta](https://capacitorjs.com/blog/announcing-capacitor-3-0-beta). In this new version the native plugins have been removed from the core and there are some changes that are necessary in the existing plugins.

**Example: Plugin Imports**
The Plugins object is deprecated, but will continue to work in Capacitor 3. Capacitor plugins should be updated to use the new plugin registration APIs (see the Upgrade Guide for plugins), which will allow them to be imported directly from the plugin’s package.

Going forward, the Plugins object from @capacitor/core should not be used.

```
// OLD
import { Plugins } from '@capacitor/core';
const { AnyPlugin } = Plugins;
Importing the plugin directly from the plugin’s package is preferred, but the plugin must be updated to work with Capacitor 3 for this to be possible.
```

```
// NEW
import { AnyPlugin } from 'any-plugin';
```

**References:**

[Updating Capacitor to 3.0 in your plugin](https://capacitorjs.com/docs/v3/updating/plugins/3-0)

[Updating Capacitor to 3.0 in your app](https://capacitorjs.com/docs/v3/updating/3-0)

**Comment by thomasvidas** [comment]
Published as `1.0.0-alpha.0` on npm. You can install with `npm i @capacitor-community/firebase-analytics@next`. Leaving this issue open until the full Capacitor 3 release

**Comment by Linknpay** [comment]
hello,
there is an issue building capacitor 3 with this plugin : 
```
Error: node_modules/@capacitor/core/types/definitions-internal.d.ts:15:18 - error TS2430: Interface 'CapacitorInstance' incorrectly extends interface 'CapacitorGlobal'.
  Types of property 'Plugins' are incompatible.
    Type '{ [pluginName: string]: { [prop: string]: any; }; }' is missing the following properties from type 'PluginRegistry': FirebaseAnalytics
```
Solution :
in file :  `node_modules/@capacitor-community/firebase-analytics/dist/esm/definitions.d.ts`
You should delete lines 1 to 5

**Comment by brownoxford** [comment]
Thanks for the report @Linknpay , I will review as soon as I can.

**Comment by ptmkenny** [comment]
Another issue related to Capacitor 3-- when using `firebase-analytics@next` (1.0-alpha2) with Capacitor 3 (official release), when I try to build my app in XCode, I get the following error about needing to update the deployment target to iOS 12:

`/Users/me/ionic/node_modules/@capacitor-community/firebase-analytics/ios/Plugin/Plugin.swift:2:8: Compiling for iOS 11.0, but module 'Capacitor' has a minimum deployment target of iOS 12.0: /Users/edo/Library/Developer/Xcode/DerivedData/App-eorluqvlqjclhjatblkywyvzklmq/Build/Products/Debug-iphoneos/Capacitor/Capacitor.framework/Modules/Capacitor.swiftmodule/arm64-apple-ios.swiftmodule`

**Comment by salohcin714** [comment]
I am actually getting same error as @Linknpay when trying to build on Capacitor 2.4.7 as well with `firebase-analytics@0.3.0`

**Comment by Linknpay** [comment]
Hello, Capacitor is no more in beta version. Can you update the plugin please. I am still getting the same error :

```
Error: node_modules/@capacitor/core/types/definitions-internal.d.ts:16:18 - error TS2430: Interface 'CapacitorInstance' incorrectly extends interface 'CapacitorGlobal'.
  Types of property 'Plugins' are incompatible.
    Type '{ [pluginName: string]: { [prop: string]: any; }; }' is missing the following properties from type 'PluginRegistry': FirebaseAnalytics

```

**Comment by brownoxford** [comment]
@ptmkenny Capacitor 3 supports iOS 12+, Capacitor 2 supported iOS 11+, so the error about deployment target is expected.
@salohcin714 You are likely getting this error because of #72, please let me know if v0.3.1 resolves it for capacitor 2.4.7

**Comment by vanessag** [comment]
@brownoxford Will this plugin be available for capacitor 3?

**Comment by brownoxford** [comment]
@vanessag Yes, definitely. I'm currently working on the 1.0.0 release that will be compatible with Capacitor 3

**Comment by brownoxford** [comment]
@Linknpay please try `v1.0.0.alpha.3`

**Comment by vkyeswa** [comment]
`v1.0.0.alpha.4` the `CapacitorCommunityFirebaseAnalytics.podspec` still has `s.ios.deployment_target  = '11.0'` instead of `12.0`

**Comment by brownoxford** [comment]
@all-contributors please add @vkyeswa for bug

**Comment by brownoxford** [comment]
> `v1.0.0.alpha.4` the `CapacitorCommunityFirebaseAnalytics.podspec` still has `s.ios.deployment_target = '11.0'` instead of `12.0`

Thanks for pointing that out! Please try `1.0.0-alpha.5`

**Comment by ultimate-tester** [comment]
Alpha.5 is giving me 

```
import { registerPlugin } from "@capacitor/core";
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

I am using this in combination with browserify, worked fine for any plugin so far except this one :)

**Comment by brownoxford** [comment]
@ultimate-tester can you show me exactly how you have browserify configured in your project so that I can try to reproduce this?

**Comment by ultimate-tester** [comment]
Hi @brownoxford  thanks for taking the time to reply, I don't have any configuration to influence the behavior of Browserify, so I'm pretty much running the out-of-the-box version. I am "building" my app using gulp-bro like so:

```
const path = require('path');
const gulp = require('gulp');
const bro = require('gulp-bro');

gulp.task('browserify', () =>
    gulp.src(path.join(__dirname, '/src/app.js')).
        pipe(bro()).
        pipe(gulp.dest(path.join(__dirname, '/www/javascripts/'))));
```

The app.js file that is going into browserify references other classes, but the FirebaseAnalytics code is actually in the root app.js file.
Now, the file contains the code which looks like this, majorly redacted:

```
const {FirebaseAnalytics} = require('@capacitor-community/firebase-analytics');

await FirebaseAnalytics.initializeFirebase({
    apiKey: '',
    authDomain: '.firebaseapp.com',
    databaseURL: 'https://.firebaseio.com',
    projectId: '',
    storageBucket: '.appspot.com',
    messagingSenderId: '',
    appId: '',
    measurementId: '',
  });

  await FirebaseAnalytics.setCollectionEnabled({
    enabled: false,
  });
```

The problem is most likely in the fact that I'm requiring instead of importing the file, I don't really have a choice though. As the other plugins work fine, I'm wondering if it's a matter of configuration in the package.json of the firebase-analytics plugin that makes it work. I'll compare this plugin's with another module that works alright and see what's the difference.

**Comment by ultimate-tester** [comment]
That didn't take too long, I found out the following:

In most plugins, the package.json file looks like this:

```
  "main": "dist/plugin.cjs.js",
  "module": "dist/esm/index.js",
```

Currently, the main of firebase-analytics is pointing to the esm module path, so the current main is not favorable.

The file located in the dist folder with the .cjs.js extension is (as the name suggests) especially for CommonJS format, the format that I'm using (with the older require() syntax).

My suggestion is to have the main and module attributes in the package.json file. The plugin.cjs.js file can look like below:

[plugin.cjs.js.txt](https://github.com/capacitor-community/firebase-analytics/files/6541695/plugin.cjs.js.txt)

I've tested it and verified it to be working. I've taken the Share plugin as a reference which is part of the official plugins. If it helps, I can make a pull request.

**Comment by brownoxford** [comment]
Interesting. I looks like new plugins created via `npm init @capacitor/plugin` follow the format you are suggesting. This plugin is pulling an old package.json along into capacitor v3, so I'll do some comparison against the new format and see if anything else needs to change. For this particular issue that you have reported, PR would be welcome.

**Comment by ultimate-tester** [comment]
Apologies in advance for messing with your repo, I have a pull request ready at #89.
I had no idea that those files were auto-generated, so this turned out easier than expected.

**Comment by ptmkenny** [comment]
> 
> 
> > `v1.0.0.alpha.4` the `CapacitorCommunityFirebaseAnalytics.podspec` still has `s.ios.deployment_target = '11.0'` instead of `12.0`
> 
> Thanks for pointing that out! Please try `1.0.0-alpha.5`

@brownoxford  I updated to `1.0.0-alpha.5`, ran `cap sync`, and rebuilt in XCode.  Same error about deployment_target as 11 instead of 12.

**EDIT**: False alarm.  Restarting XCode fixed the error.  I'm no longer getting the warning with alpha5.
